name: Build and Deploy Laravel App to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run Laravel optimizations
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: php-app
          path: |
            ./
            !vendor/bin/**
            !tests/**

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v3
        with:
          name: php-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <YOUR_APP_NAME>
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
